contact_links:
  - name: General Questions and Help
    url: https://github.com/datalust/seq-tickets/discussions/new
    about: General questions about performance, setup, etc. are welcome! Please start a thread under Discussions.
    
